### ISSUE TITLE
I met some error when I enable this plugin

### ISSUE THREAD

**Issue by xzyone** [FriendsOfFlarum/geoip#1]
after enable, the flarum is work but when I try to open discussion page, it shows:

```
Notice: Trying to get property 'is_closed' of non-object in /www/wwwroot/qepe/vendor/hiqstd/flarum-ext-close/src/Access/PostPolicy.php on line 31

Notice: Trying to get property 'is_closed' of non-object in /www/wwwroot/qepe/vendor/hiqstd/flarum-ext-close/src/Access/PostPolicy.php on line 40

Notice: Trying to get property 'is_closed' of non-object in /www/wwwroot/qepe/vendor/hiqstd/flarum-ext-close/src/Access/PostPolicy.php on line 49

Notice: Trying to get property 'is_closed' of non-object in /www/wwwroot/qepe/vendor/hiqstd/flarum-ext-close/src/Access/PostPolicy.php on line 58

Fatal error: Uncaught Zend\HttpHandlerRunner\Exception\EmitterException: Output has been emitted previously; cannot emit response in /www/wwwroot/qepe/vendor/zendframework/zend-httphandlerrunner/src/Exception/EmitterException.php:23 Stack trace: #0 /www/wwwroot/qepe/vendor/zendframework/zend-httphandlerrunner/src/Emitter/SapiEmitterTrait.php(39): Zend\HttpHandlerRunner\Exception\EmitterException::forOutputSent() #1 /www/wwwroot/qepe/vendor/zendframework/zend-httphandlerrunner/src/Emitter/SapiEmitter.php(26): Zend\HttpHandlerRunner\Emitter\SapiEmitter->assertNoPreviousOutput() #2 /www/wwwroot/qepe/vendor/zendframework/zend-httphandlerrunner/src/RequestHandlerRunner.php(97): Zend\HttpHandlerRunner\Emitter\SapiEmitter->emit(Object(Zend\Diactoros\Response\HtmlResponse)) #3 /www/wwwroot/qepe/vendor/flarum/core/src/Http/Server.php(46): Zend\HttpHandlerRunner\RequestHandlerRunner->run() #4 /www/wwwroot/qepe/public/index.php(22): Flarum\Http\Server->listen() #5 {main} thrown in /www/wwwroot/qepe/vendor/zendframework/zend-httphandlerrunner/src/Exception/EmitterException.php on line 23
```

**Comment by luceos** [comment]
This relates to hiqstd/flarum-ext-close not this extension.
